version: 0.2
phases:
  install:
    commands:
      - echo "install command"
      - cd src
      - dotnet restore
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - echo "build command"
      - dotnet build
  post_build:
    commands:
      - echo "post_build step"
artifacts:
  files:
    - '**/*'
  base-directory: 'src/DemoApi'