version: 0.2
phases:
  install:
    commands:
      - npm install -g serverless
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - echo "build command"
      - cd src
      - serverless deploy -v
  post_build:
    commands:
      - echo "post_build step"